import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { VercelToolbar } from '@vercel/toolbar/next';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const shouldInjectToolbar = process.env.NODE_ENV === 'development';
  return (
    <html lang="nl-BE">
      <body className={inter.className}>
        <Providers>
          <main>{children}</main>
        </Providers>
        {shouldInjectToolbar && <VercelToolbar />}
      </body>
    </html>
  );
}
