import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Tools from "@/components/Tools";
import Hosts from "@/components/Hosts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl-BE">
      <body className={inter.className}>
          <Providers>
            {children}
            <Hosts />
            <Tools />
          </Providers>
      </body>
    </html>
  );
}
