import '@/styles/globals.css'
import {inter} from "@/styles/fonts";
import {Toaster} from "@/components/ui/Toaster";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return <html lang="nl-BE">
    <body className={inter.className + " overscroll-none"}>
    {children}
    <Toaster/>
    </body>
    </html>
}
