-- Migration: Disable RLS on specified tables

ALTER TABLE categories    DISABLE ROW LEVEL SECURITY;
ALTER TABLE halls         DISABLE ROW LEVEL SECURITY;
ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE products      DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservations  DISABLE ROW LEVEL SECURITY;
ALTER TABLE timeslots     DISABLE ROW LEVEL SECURITY;
ALTER TABLE users         DISABLE ROW LEVEL SECURITY;